config/routes.rb
Rails.application.routes.draw do
  root 'sites#index'

  get '/plugins/sync', to: 'plugins#sync'
  get '/sites/sync', to: 'sites#sync_all', as: "sites_sync"
  get '/sites/:id/sync', to: "sites#sync_each", as: "site_sync"
  get '/sites/api', to: "sites#api", as: "site_api"

  resources :plugins, only: [:index]
  resources :sites

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plugin.rb
class Plugin < ApplicationRecord
    has_many :plugin_trackers
    has_many :sites, through: :plugin_trackers

    validates :name, presence: true
    validates :latest_version, presence: true
end

app/models/plugin_tracker.rb
class PluginTracker < ApplicationRecord
    belongs_to :site
    belongs_to :plugin

    validates :current_version, presence: true
end

app/models/site.rb
class Site < ApplicationRecord
    has_many :plugin_trackers
    has_many :plugins, through: :plugin_trackers

    validates :name, presence: true
    VALID_DOMAIN_REGEX = /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix
    validates :domain, presence: true, format: { with: VALID_DOMAIN_REGEX }
    validates :port, presence:true, uniqueness: true
    validates :database_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plugins_controller.rb
require "http"

class PluginsController < ApplicationController
  before_action :set_plugin, only: [:show, :edit, :update, :destroy]

  # GET /plugins
  # GET /plugins.json
  def index
    @plugins = Plugin.all
    @pluins
  end

  # GET /plugins/1
  # GET /plugins/1.json
  def show
  end

  # GET /plugins/new
  def new
    @plugin = Plugin.new
  end

  # GET /plugins/1/edit
  def edit
  end

  # POST /plugins
  # POST /plugins.json
  def create
    @plugin = Plugin.new(plugin_params)

    respond_to do |format|
      if @plugin.save
        format.html { redirect_to @plugin, notice: 'Plugin was successfully created.' }
        format.json { render :show, status: :created, location: @plugin }
      else
        format.html { render :new }
        format.json { render json: @plugin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plugins/1
  # PATCH/PUT /plugins/1.json
  def update
    respond_to do |format|
      if @plugin.update(plugin_params)
        format.html { redirect_to @plugin, notice: 'Plugin was successfully updated.' }
        format.json { render :show, status: :ok, location: @plugin }
      else
        format.html { render :edit }
        format.json { render json: @plugin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plugins/1
  # DELETE /plugins/1.json
  def destroy
    @plugin.destroy
    respond_to do |format|
      format.html { redirect_to plugins_url, notice: 'Plugin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sync
    url = "http://prontotools.pi.bypronto.com/api/pronto/get_all_woocommerce_plugins_and_latest_version/"
    response = HTTP.get(url)
    redirect_to plugins_url and return unless response.status.success?
    all_plugins = response.parse['plugins']
    all_plugins.each do |name, version|
        Plugin.find_or_initialize_by(name: name).update_attributes(
          {latest_version: version}
        )
    end
    respond_to do |format|
      flash[:success] = "All Plugins was successfully updated lastest version." 
      format.html { redirect_to plugins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plugin
      @plugin = Plugin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plugin_params
      params.require(:plugin).permit(:name, :latest_version)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
    @contexts = []
    @sites.each do |site|
      need_update = false
      installed_plugins = site.plugin_trackers.all
      installed_plugins.each do |installed_plugin|
        if installed_plugin.current_version != installed_plugin.plugin.latest_version
          need_update = true
          break
        end
      end
      @contexts << {site: site, need_update: need_update}
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @plugin_trackers = @site.plugin_trackers.all
  end

  # GET /sites/api
  def api
    render json: Site.all
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        flash[:success] = 'Site was successfully created.'
        format.html { redirect_to @site}
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        flash[:success] = "Site was successfully updated."
        format.html { redirect_to @site }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sync_all
    sites = Site.all
    sites.each do |site|
      url = URI.join(site.domain, "/api/pronto/get_active_woocommerce_plugins_and_version/")
      response = HTTP.get(url)
      next unless response.status.success?
      all_plugins = response.parse['plugins']
      all_plugins.each do |name, version|
        plugin = Plugin.find_by(name: name)
        flash[:danger] = "Please install \"#{name}\" plugin in ProntoTools PI."
        redirect_to sites_url and return if plugin.nil?
        site.plugin_trackers.find_or_initialize_by(
          plugin: plugin
        ).update_attributes({current_version: version})
      end
    end
    respond_to do |format|
      flash[:success] = 'All Plugins version was successfully updated for each site.'
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  def sync_each
    site = set_site
    url = URI.join(site.domain, "/api/pronto/get_active_woocommerce_plugins_and_version/")
    response = HTTP.get(url)
    redirect_to site_url and return unless response.status.success?
    all_plugins = response.parse['plugins']
    all_plugins.each do |name, version|
      plugin = Plugin.find_by(name: name)
      flash[:danger] = "Please install \"#{name}\" plugin in ProntoTools PI."
      redirect_to site_url and return if plugin.nil?
      
      site.plugin_trackers.find_or_initialize_by(
        plugin: plugin
      ).update_attributes({current_version: version})
    end
    respond_to do |format|
      flash[:danger] = "All Plugins version was successfully updated for #{site.name}."
      format.html { redirect_to site_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:name, :domain, :port, :database_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plugins_helper.rb
module PluginsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%> | ProntoTools WooNotifier</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-static-top">
        <a class="navbar-brand" href="#">ProntoTools WooNotifier</a>
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <%= link_to "Sites", sites_url, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Plugins", plugins_url, :class => "nav-link" %>
          </li>
        </ul>
      </nav>

    <div id="wrap">
      <div id="main" class="container clear-top">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div> <!-- /container -->
    </div>
  </body>
</html>

app/views/plugins/_form.html.erb
<%= form_for(plugin) do |f| %>
  <% if plugin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plugin.errors.count, "error") %> prohibited this plugin from being saved:</h2>

      <ul>
      <% plugin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :latest_version %>
    <%= f.text_field :latest_version %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plugins/edit.html.erb
<h1>Editing Plugin</h1>

<%= render 'form', plugin: @plugin %>

<%= link_to 'Show', @plugin %> |
<%= link_to 'Back', plugins_path %>

app/views/plugins/index.html.erb
<% provide(:title, 'All Plugins') %>
<div class="row m-b-15">
  <div class="col-md-12">
    <div class="inline-headers">
      <h1>Plugins (<%= @plugins.count %>)</h1>
      <%= link_to 'Sync', plugins_sync_path, class: "pull-right btn btn-success", id: "sync_btn"%>
    </div>
</div>

<table data-classes="table table responsive" data-toggle="table" data-search='true'>
  <thead>
    <tr>
      <th data-sortable="true">Name</th>
      <th data-sortable="true">Sites Installed</th>
      <th data-sortable="true">Latest version</th>
    </tr>
  </thead>

  <tbody>
    <% @plugins.each do |plugin| %>
      <tr>
        <td><%= plugin.name %></td>
        <td><%= plugin.plugin_trackers.all.count %></td>
        <td><%= plugin.latest_version %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/plugins/new.html.erb
<h1>New Plugin</h1>

<%= render 'form', plugin: @plugin %>

<%= link_to 'Back', plugins_path %>

app/views/plugins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plugin.name %>
</p>

<p>
  <strong>Latest version:</strong>
  <%= @plugin.latest_version %>
</p>

<%= link_to 'Edit', edit_plugin_path(@plugin) %> |
<%= link_to 'Back', plugins_path, class: 'btn' %>

app/views/shared/_error_messages.html.erb
<% if site.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:
    </div>
    <ul>
    <% site.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/sites/_form.html.erb
<%= form_for(site) do |f| %>
    <%= render 'shared/error_messages', site: site %>
    <div class="box-body">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :domain %>
      <%= f.text_field :domain, class: 'form-control' %>

      <%= f.label :port %>
      <%= f.text_field :port, class: 'form-control' %>

      <%= f.label :database_name %>
      <%= f.text_field :database_name, class: 'form-control' %>
    </div>
    <div class="box-footer">
      <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/sites/edit.html.erb
<% provide(:title, 'Edit Site') %>
<div class="row m-b-15">
  <div class="col-md-12">
    <div class="inline-headers">
      <h1>Editing Site</h1>
      <%= link_to 'Back', sites_path, class:"btn btn-default pull-right" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <%= render 'form', site: @site %>
  </div>
</div>

app/views/sites/index.html.erb
<% provide(:title, 'All Sites') %>
<div class="row m-b-15">
  <div class="col-md-12">
    <div class="inline-headers">
      <h1>Sites (<%= @sites.count %>)</h1>
      <div class="pull-right">
        <%= link_to 'Sync', sites_sync_path, class: "btn btn-success", id: "sync_btn"%>
        <%= link_to 'New Site', new_site_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>


<table data-classes="table table responsive" data-toggle="table" data-search='true' data-sort-name="status" data-sort-order="asc">
  <thead>
    <tr>
      <th data-sortable="true">Name</th>
      <th data-sortable="true">Domain</th>
      <th data-sortable="true">Port</th>
      <th data-sortable ="true"  data-field="status">Status</th>
      <th>Manage</th>
    </tr>
  </thead>

  <tbody>
    <% @contexts.each do |context| %>
      <tr>
        <td><%= link_to context[:site].name, context[:site] %></td>
        <td><%= link_to context[:site].domain, context[:site].domain, target: "_blank" %></td>
        <td><%= context[:site].port %></td>
        <td>
          <% if context[:need_update] %>
            <i class="fa fa-frown-o fa-2x" aria-hidden="true"></i>
          <% else %>
            <i class="fa fa-smile-o fa-2x" aria-hidden="true"></i>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_site_path(context[:site]), class: "btn btn-info btn-sm" %> <%= link_to 'Destroy', context[:site], method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sites/new.html.erb
<% provide(:title, 'New Site') %>
<div class="row m-b-15">
  <div class="col-md-12">
    <div class="inline-headers">
      <h1>New Site</h1>
      <%= link_to 'Back', sites_path, class:"btn btn-default pull-right" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <%= render 'form', site: @site %>
  <div>
</div>

<!-- <div class="row">
  <div class="col-md-12">
    <div class="inline-headers">
      <h1>New Site</h1>
      <%= link_to 'Back', sites_path, class:"btn btn-default pull-right" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form', site: @site %>
  </div>
</div> -->

app/views/sites/show.html.erb
<% provide(:title, @site.name) %>
<div class="panel panel-default">
  <div class="panel-heading">
      <div class="pull-right">
        <%= link_to 'Back', sites_path, class: "btn btn-default" %>
        <%= link_to 'Sync', site_sync_path, class: "btn btn-success", id: "sync_btn" %>
        <%= link_to 'Edit', edit_site_path(@site), class: "btn btn-primary" %>
      </div>
      <h3><%= @site.name %></h3>
  </div>

  <div class="panel-body">
    <p>
      <strong>Domain:</strong>
      <%= @site.domain %>
    </p>
    <p>
      <strong>Port:</strong>
      <%= @site.port %>
    </p>
    <p>
      <strong>Database Name:</strong>
      <%= @site.database_name %>
    </p>
  </div>
  <table data-classes="table table responsive" data-toggle="table" data-search='true'>
    <thead>
      <tr>
        <th data-sortable="true">Plugin</th>
        <th data-sortable="true">Current Version</th>
        <th data-sortable="true">Latest Version</th>
      </tr>
    </thead>
    <tbody>
      <% @plugin_trackers.each do |plugin_tracker| %>
        <tr <% if plugin_tracker.current_version != plugin_tracker.plugin.latest_version%> class="bg-danger" <% end %>>
          <td><%= plugin_tracker.plugin.name %></td>
          <td><%= plugin_tracker.current_version %></td>
          <td><%= plugin_tracker.plugin.latest_version %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>